### ISSUE TITLE
[Bug] Exomod-packager ate my hopeye

### ISSUE THREAD

**Issue by eskolnik** [suzicurran/ExomodPackager#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Details (please complete the following information):**
 - Game Version: [e.g. 22] (Found in Steam under the game's Properties)
 - Exomod-packager Version: [e.g. 1.0]

**Additional context**

**Comment by suzicurran** [comment]
Can't reproduce, please provide one additional hopeye for testing purposes.
